name: algo_lab
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  go_router: ^17.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  line_icons: ^2.0.3
  flutter_localization: ^0.3.3
  shared_preferences: ^2.5.3
  get_it: ^9.2.0
  cached_network_image: 3.4.1
  shimmer: 3.0.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_analytics: ^12.1.0
  cloud_firestore: any
  google_sign_in: ^7.2.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.1
  device_info_plus: ^12.3.0
  local_auth: ^3.0.0
  logger: ^2.5.0
  envied: ^1.2.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  envied_generator: ^1.2.0
  build_runner: ^2.4.13
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/localization/

  # To add custom fonts to your application, add a fonts section here,
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#3DDC84"
  size: 45
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

